voxel_size: 0.06
normals:
  radius_multiplier: 1.0
  max_nn: 50
features:
  radius_multiplier: 8.0
  max_nn: 150
ransac:
  distance_multiplier: 0.8
  ransac_n: 5
  edge_length_threshold: 0.95
  max_iterations: 20000
  confidence: 0.9999
icp:
  distance_threshold: 0.015
  max_iterations: 1000
robust_kernel:
  type: Tukey
  k: 0.08
